### ISSUE TITLE
Gifted and incompetent skills in GUI

### ISSUE THREAD

**Issue by MirUlr** [MirUlr/dsa_calculator#15]
Class `Hero` provide automatical management of _Begabungen_ and _Unfähigkeiten_, if they were specified correctly. Methods `get_gifted_skills_gui()` and `get_incompetent_skills_gui()` provide possibility to process these information in graphical user interface.

It is hereby proposed to use checkboxes for marking a roll on an skill/spell-like as gifted. This proposal is motivated by the circumstance, that the effect of gifted also be caused by several mechanics, e.g. [_Stärkungssegen_](https://ulisses-regelwiki.de/index.php/Seg_St%C3%A4rkungssegen.html) or [_Weisheitssegen_](https://ulisses-regelwiki.de/index.php/SeG_Weisheitssegen.html).

Summarized behavior:
- Every skill or spell-like provide a checkbox to mark it as gifted
- After execution of the test, the correspondig checkbox is unchecked
- Inherent gifted skills (see `Held.get_gifted_skills_gui()`) are ckeckd as default and can not be unchecked by user
- Inherent gifted skills are not unchecked after execution of test

**Comment by MirUlr** [comment]
@Ithiliel What is your opinon on this?

**Comment by MirUlr** [comment]
@MirUlr `Held.absolviere(talent, modifikator)` shall be extened by keyword argument for those temporal gifted talents.

**Comment by RabeaSennlaub** [comment]
The functionality sounds good. Maybe the GUI Layout needs to get adjusted, so it will not be to crowded with yet another column.

**Comment by MirUlr** [comment]
After revisitng the rulebook it seems unnecessary to implement the concept of temporal gifted/incompetent skills.

Reason:
All (at least most) events, which cause the temporal gifted effect, need the player to confirm the reroll (and also to pick the specific dice).
Therefore the user need to be asked, whether or not the effect of gifted shall be used. This would raise the need to rework `Hero` in an extensive way; e.g. remember the past (and only this) roll. On the other hand, the operation of such a multi-stage-dialogue for one roll is not intuitive.

Therefore the objective of this issue changes to the implementation of the possibility to state skills and spell-likes as _gifted_ and _incompetnet_ in `makeHero.py`. Further these permanent affected abilities should be vizually marked in `GUI.py`.

**Comment by MirUlr** [comment]
Closed du to creating of #31 and push of bcb597b
